### ISSUE TITLE
Unknown filter category: unwatched

### ISSUE THREAD

**Issue by Webreaper** [wilmardo/migrate-plex-to-jellyfin#10]
Running this works for films, but for TV shows I get the error:

Unknown filter category: unwatched

Any idea why?

**Comment by wilmardo** [comment]
Thanks for opening an issue!
I will try to recreate this later this evening, there has been a major version bump of the plexapi module last May so that might have something to do with it but that is just a hunch. There is no changelog to go from so I will go and test :)

**Comment by Webreaper** [comment]
Ah, I did wonder whether I should try and pull an older version of
plex-api.py...
