### ISSUE TITLE
Error at running the python3 migrate.py

### ISSUE THREAD

**Issue by Pascal2708** [wilmardo/migrate-plex-to-jellyfin#13]
After I did everything before successfully the final command python3 migrate.py... fails with:

Traceback (most recent call last):
  File "migrate.py", line 123, in <module>
    migrate()
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "migrate.py", line 44, in migrate
    plex = PlexServer(plex_url, plex_token, session=session)
  File "/home/pi/venv/lib/python3.7/site-packages/plexapi/server.py", line 110, in __init__
    data = self.query(self.key, timeout=timeout)
  File "/home/pi/venv/lib/python3.7/site-packages/plexapi/server.py", line 452, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 260, column 2

Is there something wrong in this file? I am not an advanced user to fix this by my own...
I did place it directly in venv like the other files.
The Error starts as I enter the command till the plex token.

**Comment by wilmardo** [comment]
Thanks for the issue! It might be a good idea to document the usage a bit more :+1: 

I don't know if your current issue something the code or something in your local environment. Could you retry with the these steps?

Download the repo and unpack somewhere:
https://github.com/wilmardo/migrate-plex-to-jellyfin/archive/dev.zip

Open a terminal in this folder and issue the following commands.
```
python3 -m venv venv
```
This should result in an `venv` folder being created.

To activate this virtualenv there are scripts in the `venv/bin/` folder. For linux you can source `venv/bin/activate` like this
```
source venv/bin/activate
```
On Windows it should be for cmd
```
.\venv\Scripts\activate.bat
```
for Powershell
```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
.\venv\Scripts\Activate.ps1
```

Now it is time to setup the needed dependencies:
```
pip install -r requirements.txt
```

This should setup the needed environment. In the same terminal you should be able to issue the following command without errors:

```
python3 ./migrate.py --insecure --debug --plex-url https://plex.test.com:32400 --plex-token 123123123 --jellyfin-url https://jellyfin.test.com --jellyfin-token 123123123 --jellyfin-user user
```

**Comment by wilmardo** [comment]
Here is some more information about the virtualenv:
https://docs.python.org/3/library/venv.html

It is not needed to run this script in a virtualenv but it helps to keep your host Python clean and avoid future problems

**Comment by Pascal2708** [comment]
I tried it on another system and also found an copy paste error in the Plex URL :D The error seems now my german folder "Filme"? Do I need to rename it to english films?

```
Traceback (most recent call last):
  File "./migrate.py", line 123, in <module>
    migrate()
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./migrate.py", line 53, in migrate
    plex_movies = plex.library.section('Films')
  File "/root/venv/lib/python3.7/site-packages/plexapi/library.py", line 57, in section
    raise NotFound('Invalid library section: %s' % title)
plexapi.exceptions.NotFound: Invalid library section: Films
```
I answered this my self after renaiming, Yes it helped. Now there is a new error:
```
` File "./migrate.py", line 123, in <module>
    migrate()
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./migrate.py", line 55, in migrate
    info = _extract_provider(data=m.guid)
  File "./migrate.py", line 118, in _extract_provider
    'provider': match.group(1).replace('the', '').capitalize(),  # Jellyfin uses Imdb and Tvdb
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by wilmardo** [comment]
Thanks for the feedback, the hardcoded library names are known issue. The script was something quick for myself so some shortcuts were taken ;)

About the second error I refactored the code a little to be more resilient to errors like this:
https://github.com/wilmardo/migrate-plex-to-jellyfin/archive/fix-13.zip

If you run the script with those changes it should at least log what episode did not match. Could you retry?
The new code is untested (my Plex isn't working anymore, no time to investigate a the moment), as long as you keep posting the errors we should get a result :)

**Comment by wilmardo** [comment]
If you would like to apply the diff yourself, the codechange is here:
https://github.com/wilmardo/migrate-plex-to-jellyfin/pull/14

**Comment by Pascal2708** [comment]
Thanks for this good service :)
It shows me the movie with a problem:
```
No provider match in local://6102 for Spy Lammbock
Traceback (most recent call last):
  File "./migrate.py", line 148, in <module>
    migrate()
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./migrate.py", line 69, in migrate
    plex_tvshows = plex.library.section('TV Shows')
  File "/root/venv/lib/python3.7/site-packages/plexapi/library.py", line 57, in section
    raise NotFound('Invalid library section: %s' % title)
plexapi.exceptions.NotFound: Invalid library section: TV Shows
```

Is this 1 movie really holding back the hole process? I dont really care about 1 or 2 movies which dont get matched.
Most important would be series and the most as possible of my movies.
Do I need to rename any libraries? How are the exact needed names?

I am really not good enough to change the script :D

**Comment by wilmardo** [comment]
> Is this 1 movie really holding back the hole process? I dont really care about 1 or 2 movies which dont get matched.

For this you can run the script with --skip as parameter, it then just prints the warnings and keeps going.
My guess is that you have passed this as a parameter since it completes the movie loop and errors for the tv shows since your library is named different then mine was. So we are one step further :)

It is open as an issue to remove these hardcoded values #9. You can edit the script on line 60 to match your tv show library name:

https://github.com/wilmardo/migrate-plex-to-jellyfin/blob/dev/migrate.py#L60

**Comment by Pascal2708** [comment]
> > Is this 1 movie really holding back the hole process? I dont really care about 1 or 2 movies which dont get matched.
> 
> For this you can run the script with --skip as parameter, it then just prints the warnings and keeps going.
> My guess is that you have passed this as a parameter since it completes the movie loop and errors for the tv shows since your library is named different then mine was. So we are one step further :)
> 
> It is open as an issue to remove these hardcoded values #9. You can edit the script on line 60 to match your tv show library name:
> 
> https://github.com/wilmardo/migrate-plex-to-jellyfin/blob/dev/migrate.py#L60

Thanks now I am done :)
Some series did not work but I watched them complete so no problem at all.
Great script after I changed the names + --skip parameter

Maybe move this in to the FAQ :)
