### ISSUE TITLE
Overlapping variables with debugging controls

### ISSUE THREAD

**Issue by ankenyr** [wilmardo/migrate-plex-to-jellyfin#2]
A lot of single letter variables you chose overlap with common debugger control characters which makes debugging life difficult.
The following are all the reserved words for IPython debugger which should cover the Python debugger plus a bit more

Documented commands (type help <topic>):
========================================
EOF    cl         disable  interact  next    psource  rv         unt
a      clear      display  j         p       q        s          until
alias  commands   down     jump      pdef    quit     source     up
args   condition  enable   l         pdoc    r        step       w
b      cont       exit     list      pfile   restart  tbreak     whatis
break  continue   h        ll        pinfo   return   u          where
bt     d          help     longlist  pinfo2  retval   unalias
c      debug      ignore   n         pp      run      undisplay

Miscellaneous help topics:
==========================
exec  pdb

If desired I can send a pr fixing these helping myself and others who may wish to debug in the future.
Your script is great but so far debugging it for my own use has been like[ this](https://www.youtube.com/watch?v=aRq1Ksh-32g)

**Comment by wilmardo** [comment]
@ankenyr Thanks for the pointers! I did not know this, I use the vscode debugger for my debugging which has the functions keys for control. Nice to learn something new :+1: 

If you could sent in a PR that would be great, if not I will fix this some time in the future :)

**Comment by wilmardo** [comment]
Closed with #5
